"""empty message

Revision ID: 5c8b5526c4d8
Revises: 92e8bae5b9b0
Create Date: 2016-05-05 12:39:53.519691

"""

# revision identifiers, used by Alembic.
revision = '5c8b5526c4d8'
down_revision = '92e8bae5b9b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_grids', sa.Column('chooser', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_grids', 'chooser')
    ### end Alembic commands ###
