"""empty message

Revision ID: 92e8bae5b9b0
Revises: None
Create Date: 2016-05-04 15:56:58.971549

"""

# revision identifiers, used by Alembic.
revision = '92e8bae5b9b0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_grids',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('grid', postgresql.JSONB(), nullable=True),
    sa.Column('minimize', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_grids')
    ### end Alembic commands ###
