"""empty message

Revision ID: 979e274ba2ae
Revises: 5c8b5526c4d8
Create Date: 2016-06-23 16:59:59.436710

"""

# revision identifiers, used by Alembic.
revision = '979e274ba2ae'
down_revision = '5c8b5526c4d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_grids', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('model_grids', sa.Column('name', sa.String(), nullable=True))
    op.add_column('model_grids', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_grids', 'updated_at')
    op.drop_column('model_grids', 'name')
    op.drop_column('model_grids', 'created_at')
    ### end Alembic commands ###
