"""empty message

Revision ID: d08c6339dcef
Revises: 22519132286a
Create Date: 2016-06-24 14:36:54.692866

"""

# revision identifiers, used by Alembic.
revision = 'd08c6339dcef'
down_revision = '22519132286a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('loop_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'loop_id')
    ### end Alembic commands ###
